# scanomaly/__init__.py
from __future__ import annotations

from jax import config as jax_config
jax_config.update("jax_enable_x64", True)

from .config import FinderConfig
from .criteria import CandidateCriteria
from .finder import Finder
from .models import (
    AnomalyResult,
    BestCandidate,
    CandidateQuality,
    ScoredCandidate,
    SeasonSummary,
)
from .plot import AnomalyPlotter
from .singlelens_fit import SingleLensFitResult
from .fitters import (
    PSPLFitter,
    FSPLFitter,
    PSPLParallaxFitter,
    FSPLParallaxFitter,
)
from .template_free import (
    TemplateFreeCandidate,
    TemplateFreeScanner,
    TemplateFreeSearchConfig,
    TemplateFreeSearchResult,
)
from .planet_signal import (
    FlatBaselineDiagnostic,
    FoldCausticConfig,
    FoldCausticDetector,
    FoldCausticEdge,
    FoldCausticPair,
    FoldCausticResult,
    LocalTrendChangeMasker,
    PlanetFeature,
    PlanetFeatureConfig,
    PlanetFeatureResult,
    PlanetSignalCandidate,
    PlanetSignalConfig,
    PlanetSignalExtractor,
    PlanetSignalIteration,
    PlanetSignalResult,
    PlanetSignalTiming,
    PlanetScanDecision,
    PlanetDetectionRecord,
)
from .anomaly_pipeline import (
    AnomalyCandidate,
    AnomalyPipelineConfig,
    AnomalyPipelineResult,
    build_anomaly_candidates,
)
from .signal_scale import (
    ObservedSignalScale,
    ResolvedSignalScale,
    interval_mask,
    measure_observed_signal_scale,
    resolve_event_signal_scale,
)
from .pspl_fft import (
    PSPLFFTCandidate,
    PSPLFFTProfile,
    PSPLFFTScanner,
    PSPLFFTSearchResult,
    pspl_excess_magnification,
)
from .effect_detection import (
    EffectCandidate,
    EffectMorphologyConfig,
    EffectMorphologyScores,
    ProjectionDiagnostics,
    build_fspl_template_bank,
    compute_effect_morphology_scores,
    detect_fspl_from_pspl_fit,
    detect_parallax_from_pspl_fit,
    detect_physical_effects,
    find_compact_blocks,
    parallax_score_test,
    project_out_nuisance,
)
from .fspl_initialization import fspl_template_initial_guesses
from .effect_routing import (
    RoutingThresholds,
    route_candidate,
    route_candidates,
    routing_pareto_curve,
    select_fallback_candidates,
)
from .contamination import (
    ContaminationConfig,
    ContaminationSegmentation,
    RobustFitIteration,
    RobustFitResult,
    protected_support_mask,
    scaled_parameter_distance,
    robust_refine_with_fitter,
    segment_anomaly_dp,
    segmentation_weights,
)
from .singlelens_fallback import (
    FallbackAttempt,
    FallbackConfig,
    FallbackResult,
    EffectFitterSpec,
    detector_seed_parameters,
    make_effect_fitter,
    run_robust_fallback,
    run_staged_joint_fallback,
)
from .parallax_backend import (
    TimeSpec,
    Ephemeris,
    ParallaxDiagnostics,
    ParallaxEvaluator,
    parallax_effect_score,
)
from .effect_aware import EffectAwareFinderResult, PlanetCandidateMatch, match_planet_candidates
from .exact_probe import (
    ExactProbeEvaluation,
    ExactProbeResult,
    run_exact_probe,
    run_fspl_exact_probe,
    run_parallax_exact_probe,
)

__all__ = [
    "FinderConfig",
    "CandidateCriteria",
    "Finder",
    "AnomalyResult",
    "BestCandidate",
    "ScoredCandidate",
    "CandidateQuality",
    "SeasonSummary",
    "AnomalyPlotter",
    "PSPLFitter",
    "FSPLFitter",
    "PSPLParallaxFitter",
    "FSPLParallaxFitter",
    "SingleLensFitResult",
    "TemplateFreeCandidate",
    "TemplateFreeScanner",
    "TemplateFreeSearchConfig",
    "TemplateFreeSearchResult",
    "FlatBaselineDiagnostic",
    "FoldCausticConfig",
    "FoldCausticDetector",
    "FoldCausticEdge",
    "FoldCausticPair",
    "FoldCausticResult",
    "LocalTrendChangeMasker",
    "PlanetFeature",
    "PlanetFeatureConfig",
    "PlanetFeatureResult",
    "PlanetSignalCandidate",
    "PlanetSignalConfig",
    "PlanetSignalExtractor",
    "PlanetSignalIteration",
    "PlanetSignalResult",
    "PlanetSignalTiming",
    "PlanetScanDecision",
    "PlanetDetectionRecord",
    "AnomalyPipelineConfig",
    "AnomalyPipelineResult",
    "AnomalyCandidate",
    "build_anomaly_candidates",
    "ObservedSignalScale",
    "ResolvedSignalScale",
    "interval_mask",
    "measure_observed_signal_scale",
    "resolve_event_signal_scale",
    "PSPLFFTCandidate",
    "PSPLFFTProfile",
    "PSPLFFTScanner",
    "PSPLFFTSearchResult",
    "pspl_excess_magnification",
    "EffectCandidate",
    "EffectMorphologyConfig",
    "EffectMorphologyScores",
    "ProjectionDiagnostics",
    "build_fspl_template_bank",
    "compute_effect_morphology_scores",
    "detect_fspl_from_pspl_fit",
    "detect_parallax_from_pspl_fit",
    "detect_physical_effects",
    "find_compact_blocks",
    "parallax_score_test",
    "project_out_nuisance",
    "fspl_template_initial_guesses",
    "RoutingThresholds",
    "route_candidate",
    "route_candidates",
    "routing_pareto_curve",
    "select_fallback_candidates",
    "ContaminationConfig",
    "ContaminationSegmentation",
    "RobustFitIteration",
    "RobustFitResult",
    "protected_support_mask",
    "scaled_parameter_distance",
    "robust_refine_with_fitter",
    "segment_anomaly_dp",
    "segmentation_weights",
    "FallbackAttempt",
    "FallbackConfig",
    "FallbackResult",
    "EffectFitterSpec",
    "detector_seed_parameters",
    "make_effect_fitter",
    "run_robust_fallback",
    "run_staged_joint_fallback",
    "TimeSpec",
    "Ephemeris",
    "ParallaxDiagnostics",
    "ParallaxEvaluator",
    "parallax_effect_score",
    "EffectAwareFinderResult",
    "PlanetCandidateMatch",
    "match_planet_candidates",
    "ExactProbeEvaluation",
    "ExactProbeResult",
    "run_exact_probe",
    "run_fspl_exact_probe",
    "run_parallax_exact_probe",
]

__version__ = "0.5.3"
